query GetBreed($name: String!) {
  breed(name: $name) {
    id
    name
    description
    image
    temperament
    origin
    lifeSpan
    adaptability
    affectionLevel
    childFriendly
    grooming
    intelligence
    healthIssues
    socialNeeds
    strangerFriendly
    photos {
      url
    }
  }
}
