type Query {
  breeds(limit: Int, page: Int): [Breed!]!
  breed(name: String!): Breed!
}

type Breed {
  id: ID!
  name: String!
  description: String!
  temperature: String!
  origin: String!
  lifeSpan: String!
  adaptability: Int!
  affectionLevel: Int!
  childFriendly: Int!
  grooming: Int!
  intelligence: Int!
  healthIssues: Int!
  socialNeeds: Int!
  strangerFriendly: Int!
  image: String!
  photos: [Image!]!
}

type Image {
  id: ID!
  height: Int!
  width: Int!
  url: String!
}
